name: Keep Upstash Alive
on:
  schedule:
    - cron: '0 0 */7 * *'
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Redis grok2api
        run: |
          curl https://major-raptor-66514.upstash.io/ping \
            -H "Authorization: Bearer ${{ secrets.GROK2API }}"

      # - name: Ping Redis DB2
      #   run: curl ${{ secrets.UPSTASH_URL_2 }}/ping -H "Authorization: Bearer ${{ secrets.UPSTASH_TOKEN_2 }}"

      # - name: Ping Redis DB3
      #   run: curl ${{ secrets.UPSTASH_URL_3 }}/ping -H "Authorization: Bearer ${{ secrets.UPSTASH_TOKEN_3 }}"
